version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_TYPE=postgres
      - DATABASE_NAME=messages
      - DATABASE_USER_NAME=postgres
      - DATABASE_USER_PASSWORD=admin
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: "postgres"
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=messages
volumes:
  pgdata: {}
